film_database_10/fdb_10/fdb_10/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

film_database_10/fdb_10/index_app/urls.py
from django.urls import path
from index_app import views
app_name = "filmapp"

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:film_id>/', views.detail, name="detail"),
    path('add_film/', views.add_film, name='add_film'),
    path('update/', views.redirect_f, name='redirect'),
    path('delete/', views.redirect_f, name='redirect'),
    path('update/<int:id>/', views.update_film, name='update'),
    path('delete/<int:id>/', views.delete_film, name='delete'),
]

film_database_10/fdb_10/index_app/models.py
from django.db import models


# Create your models here.

class Film(models.Model):
    f_name = models.CharField(max_length=250)
    f_year = models.CharField(max_length=250)
    f_genre = models.CharField(max_length=250)
    f_prate = models.CharField(max_length=250)
    f_cast = models.CharField(max_length=250)
    f_dir = models.CharField(max_length=250)
    f_plot = models.TextField()
    f_img = models.ImageField(upload_to='pics')

    def __str__(self):
        return self.f_name

film_database_10/fdb_10/index_app/forms.py
from django import forms
from .models import Film

class FilmForm(forms.ModelForm):
    class Meta:
        model = Film
        fields = ['f_name', 'f_year', 'f_genre', 'f_prate', 'f_cast', 'f_cast', 'f_dir', 'f_plot', 'f_img']

film_database_10/fdb_10/index_app/views.py
from django.shortcuts import render, redirect
from .models import Film
from .forms import FilmForm


# Create your views here.

def index(request):
    film = Film.objects.all()
    return render(request, 'index.html', {'film_list': film})


def detail(request, film_id):
    film = Film.objects.get(id=film_id)
    return render(request, 'detail.html', {'film_list': film})

def redirect_f(request):
    return redirect('/')


def add_film(request):
    if request.method == "POST":
        f_name = request.POST.get('name',)
        f_year = request.POST.get('year',)
        f_genre = request.POST.get('genre',)
        f_prate = request.POST.get('prate',)
        f_cast = request.POST.get('cast',)
        f_dir = request.POST.get('dir',)
        f_plot = request.POST.get('plot',)
        f_img = request.FILES['img']
        film = Film(f_name=f_name, f_year=f_year, f_genre=f_genre, f_prate=f_prate, f_cast=f_cast, f_dir=f_dir, f_plot=f_plot, f_img=f_img)
        film.save()
        return redirect('/')
    return render(request, 'add_film.html')


def update_film(request,id):
    film = Film.objects.get(id=id)
    form = FilmForm(request.POST or None, request.FILES, instance=film)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'update.html', {'form': form, 'film': film})

def delete_film(request,id):
    if request.method == "POST":
        film = Film.objects.get(id=id)
        film.delete()
        return redirect('/')
    return render(request, 'delete.html')

film_database_10/fdb_10/templates/add_film.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
	<title>
        Add a film
	</title>
</head>
<style>
	.a1
	{
	position:static;
	border-radius:2px;
	margin:auto;
	padding:10px;
	width:95%;
	height:auto;
	background-color:#77ab91;
	}

	.a2
	{
	border: solid grey;
	border-radius:2px;
	margin:auto;
	padding:10px;
	width:95%;
	height:auto;
	background-color:white;
	}

	.image1
	{
	min-width:300px;
	height:180px;
	object-fit:cover;
	}

	.container
	{
	border-radius:2px;
	position:relative;
	padding:6px;
	width:85%;
	height:100%;
	background-color:#e4e4e4;
	}
</style>

<body style="font-family:century gothic;">
<div class="container">
    <div class="row1">
        <div class="col-sm-12">
	    <br><div class="a1">
                <h1 style="margin-left:25px;">Add a film</h1>
            </div>
	    </div>
    </div>
    <div class="row2">
	    <div class="col-sm-12">
            <br><div class="a2">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="text" name="name" placeholder="Name of film"><br><br>
                <input type="text" name="year" placeholder="Year of Release"><br><br>
                <input type="text" name="genre" placeholder="Genre"><br><br>
                <input type="text" name="prate" placeholder="CBFC Rating"><br><br>
                <input type="text" name="cast" placeholder="Cast"><br><br>
                <input type="text" name="dir" placeholder="Director"><br><br>
                <input type="text" name="plot" placeholder="Plot"><br><br>
                <input type="file" name="img"><br><br>
                <input type="submit">
            </form>

            </div>
        </div>
    </div>
</div>
</body>
</head>
</html>

film_database_10/fdb_10/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

</head>
<style>
	.a1
	{
	position:static;
	border-radius:2px;
	margin:auto;
	padding:10px;
	width:95%;
	height:auto;
	background-color:#77ab91;
	}

	.a2
	{
	border: solid grey;
	border-radius:2px;
	margin:auto;
	padding:10px;
	width:95%;
	height:auto;
	background-color:white;
	}

	.image1
	{
	min-width:300px;
	height:180px;
	object-fit:cover;
	}

	.container
	{
	border-radius:2px;
	position:relative;
	padding:6px;
	width:85%;
	height:auto;
	background-color:#e4e4e4;
	}
</style>

<body style="font-family:century gothic;">
<div class="container">
    <div class="row1">
        <div class="col-sm-12">
	    <br><div class="a1">
            {% block body1 %}
            {% endblock %}
            </div>
	    </div>
    </div>
    <div class="row2">
	    <div class="col-sm-12">
            <br><div class="a2">
            {% block body2 %}
            {% endblock %}
            </div>
        </div>
    </div>
</div>
</body>
</head>
</html>

film_database_10/fdb_10/templates/delete.html
	<title>
        Delete Film
	</title>
{% extends "base.html" %}
    {% block body1 %}
        <h1 style="margin-left:25px;">Delete Film</h1>
    {% endblock %}

{% block body2 %}
<form method="POST">
  {% csrf_token %}
  Do you want to delete the film?
  <input type="submit">
</form>
{% endblock %}

film_database_10/fdb_10/templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
	<title>
        {{film_list.f_name}}
	</title>
</head>
<style>
	.a1
	{
	position:static;
	border-radius:1px;
	margin:auto;
	padding:10px;
	width:95%;
	height:auto;
	background-color:#77ab91;
	}

	.a2
	{
	border: solid grey;
	border-radius:1px;
	margin:auto;
	padding:10px;
	width:95%;
	height:auto;
	background-color:white;
	}

	.image1
	{
	min-width:300px;
	height:180px;
	object-fit:cover;
	}

	.container
	{
	border-radius:1px;
	position:relative;
	padding:6px;
	width:85%;
	height:100%;
	background-color:#e4e4e4;
	}
</style>

<body style="font-family:century gothic;">
<div class="container">
    <div class="row1">
        <div class="col-sm-12">
	    <br><div class="a1">
                <h1 style="margin-left:25px;">{{film_list.f_name}}</h1>
            </div>
	    </div>
    </div>
    <div class="row2">
	    <div class="col-sm-12">
            <br><div class="a2">
            <img src="{{film_list.f_img.url}}" class="image1">
            <h3 style="font-size:18px;">{{film_list.f_name}}</h3>
            <h4 style="font-size:14px;">{{film_list.f_year}}</h4>
            <h5 style="font-size:10px;">{{film_list.f_genre}} | {{film_list.f_prate}}</h5>
            <h5 style="font-size:12px;">Director: {{film_list.f_dir}}</h5>
            <h5 style="font-size:12px;">Cast: {{film_list.f_cast}}</h5>
            <p style="font-size:12px;">Plot:<br>{{film_list.f_plot}}</p>
            <a href="{% url 'filmapp:update' film_list.id %}">Update</a><br>
            <a href="{% url 'filmapp:delete' film_list.id %}">Delete</a>
            </div>
        </div>
    </div>
</div>
</body>
</head>
</html>

film_database_10/fdb_10/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
	<title>
	F - Database
	</title>
</head>
<style>
	.a1
	{
	position:static;
	border-radius:1px;
	margin:auto;
	padding:10px;
	width:95%;
	height:auto;
	background-color:#77ab91;
	}

	.a2
	{
	border: solid grey;
	border-radius:1px;
	margin:auto;
	padding:7px;
	width:200px;
	height:400px;
	background-color:white;
	}

	.image1
	{
	width:100%;
	height:180px;
	object-fit:cover;
	}

	.container
	{
	border-radius:1px;
	position:relative;
	padding:6px;
	width:85%;
	height:100%;
	background-color:#e4e4e4;
	}
</style>

<body style="font-family:century gothic;">
<div class="container">
    <div class="row1">
        <div class="col-sm-12">
	    <br><div class="a1">
                <h1 style="margin-left:25px;">Film DataBase</h1>
                <h4 style="margin-left:25px;"><a href="add_film/">Add a film</a></h4>
            </div>
	    </div>
    </div>
    <div class="row2">
        <div class="col-sm-1">
        </div>
        <div class="col-sm-10">
            <div class="row3">
            {% for i in film_list %}
	        <div class="col-sm-4">
                <br><div class="a2">
                <img src="{{i.f_img.url}}" class="image1">
                <h3 style="font-size:18px;"><a href="{{i.id}}">{{i.f_name}}</a></h3>
                <h4 style="font-size:14px;">{{i.f_year}}</h4>
                <h5 style="font-size:10px;">{{i.f_genre}} | {{i.f_prate}}</h5>
                <h5 style="font-size:12px;">Director: {{i.f_dir}}</h5>
                <h5 style="font-size:12px;">Cast: {{i.f_cast}}</h5>
                </div>
            </div>
            {% endfor %}
            </div>
        </div>
        <div class="col-sm-1">
        </div>
    </div>
</div>
</body>
</head>
</html>

film_database_10/fdb_10/templates/killbill.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
	<title>
	Kill Bill V:01
	</title>
</head>
<style>
	.a2
	{
	border: solid grey;
	border-radius:2px;
	margin:auto;
	padding:10px;
	width:100%;
	height:auto;
	background-color:white;
	}

	.container
	{
	border-radius:2px;
	position:relative;
	padding:6px;
	width:85%;
	height:100%;
	background-color:#e4e4e4;
	}
</style>

<body style="font-family:century gothic;">
<div class="container">
    <h1 style="margin-left:15px;">Kill Bill V:01</h1>
    <div class="row2">
	    <div class="col-sm-12">
            <br><div class="a2">
            <img src="1843ed69d1210ac2a70ecf0612543e62.jpeg">

            </div>
        </div>
    </div>
</div>
</body>
</head>
</html>

film_database_10/fdb_10/templates/pulpfiction.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
	<title>
	Kill Bill V:01
	</title>
</head>
<style>
	.a2
	{
	border: solid grey;
	border-radius:2px;
	margin:auto;
	padding:10px;
	width:100%;
	height:auto;
	background-color:white;
	}

	.container
	{
	border-radius:2px;
	position:relative;
	padding:6px;
	width:85%;
	height:100%;
	background-color:#e4e4e4;
	}
</style>

<body style="font-family:century gothic;">
<div class="container">
    <h1 style="margin-left:15px;">Pulp Fiction</h1>
    <div class="row2">
	    <div class="col-sm-12">
            <br><div class="a2">
            <img src="1843ed69d1210ac2a70ecf0612543e62.jpeg">

            </div>
        </div>
    </div>
</div>
</body>
</head>
</html>

film_database_10/fdb_10/templates/update.html
	<title>
        Update Details
	</title>

{% extends "base.html" %}
    {% block body1 %}
        <h1 style="margin-left:25px;">Update Details</h1>
    {% endblock %}

{% block body2 %}
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit">
</form>
{% endblock %}